### ISSUE TITLE
Remove coffeescript dependency

### ISSUE THREAD

**Issue by kirstein** [toggl/time-format-utils#2]
It would be nice to be able to use this lib without the need of CoffeeScript.

Maybe add a pre-release step which will compile CS to dist/*.js?

**Comment by yamadapc** [comment]
Yeah, we can just replace the `postinstall` hook with `prepublish`. https://docs.npmjs.com/misc/scripts

**Comment by yamadapc** [comment]
Oh... I hadn't noticed this, this means the dependencies are actually broken. Because coffee-script isn't a dependency.
